PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ncbiv: <http://bio2rdf.org/ncbigene_vocabulary:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX genagev: <http://bio2rdf.org/genage_vocabulary:>

SELECT ?gene ?label
WHERE {
	?gene rdf:type genagev:Human-Aging-Related-Gene ;
		rdfs:label ?label .
}
LIMIT 10